export const FETCH_CINEMA_CLUSTERS = "FETCH_CINEMA_CLUSTERS";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_CINEMAS = "FETCH_CINEMAS";
export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const CINEMA_CHOOSEN = "CINEMA_CHOOSEN";
export const FETCH_MOVIE_SCHEDULES = "FETCH_MOVIE_SCHEDULES";
export const FETCH_CINEMA_ID = "FETCH_CINEMA_ID";
